# Generated by Selenium IDE
import os
from dotenv import load_dotenv

from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.support import expected_conditions as expected_conditions

from selenium.webdriver.chrome.service import Service as ChromeService
from webdriver_manager.chrome import ChromeDriverManager

from selenium.webdriver.firefox.service import Service as FirefoxService


# from webdriver_manager.firefox import GeckoDriverManager


class Test411withsignin():
    load_dotenv()
    username = os.getenv("USER")
    password = os.getenv("PASS")

    def setup_method(self, method):
        print(self.username, self.password)
        # keep the window open after test is done for debugging.
        options = Options()
        options.add_experimental_option("detach", True)
        self.driver = webdriver.Chrome(service=ChromeService(ChromeDriverManager().install()), options=options)
        # self.driver = webdriver.Firefox(service=FirefoxService(GeckoDriverManager().install()))

        self.vars = {}

    def teardown_method(self, method):
        # keep the window open after test is done for debugging.
        # self.driver.quit()
        pass

    def test_411withsignin(self):
        wait = WebDriverWait(self.driver, 30)  # lmfao 30 seconds timeout GOD DAMN student link is slow

        # initial exported code:
        # Test name: 411-with-signin
        # Step # | name | target | value
        # 1 | open | https://student.bu.edu/MyBU/s/ |
        self.driver.get("https://student.bu.edu/MyBU/s/")
        # 2 | setWindowSize | 1440x819 |
        self.driver.set_window_size(1440, 819)

        # self.driver.find_element(By.CSS_SELECTOR, ".comm-tile-menu__item-title-underline").click()
        wait.until(expected_conditions.presence_of_element_located((By.ID, "j_username")))
        # 3 | type | id=j_username | username
        self.driver.find_element(By.ID, "j_username").send_keys(self.username)
        # 4 | type | id=j_password | password
        self.driver.find_element(By.ID, "j_password").send_keys(self.password)
        # 5 | click | name=_eventId_proceed |
        self.driver.find_element(By.NAME, "_eventId_proceed").click()

        # after we've signed in, we need to wait for 2fa to go through. wait until redirect
        # FIXME: we don't set "remember me" here so we have to wait for 2fa every time
        wait.until(expected_conditions.url_changes("https://student.bu.edu/MyBU/s/"))

        # student link slow, wait until loaded
        element = wait.until(expected_conditions.element_to_be_clickable(
            (By.CLASS_NAME, "community_navigation-tileMenuItemBanner_tileMenuItemBanner")))
        element.click()

        # 6 | click | css=tr:nth-child(18) a:nth-child(2) |
        self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(18) a:nth-child(2)").click()
        # 7 | click | linkText=Register for Class |
        self.driver.find_element(By.LINK_TEXT, "Register for Class").click()
        # 8 | click | name=College |
        self.driver.find_element(By.NAME, "College").click()
        # 9 | select | name=College | label=CAS
        dropdown = self.driver.find_element(By.NAME, "College")
        dropdown.find_element(By.XPATH, "//option[. = 'CAS']").click()
        # 10 | type | name=Dept | cs
        self.driver.find_element(By.NAME, "Dept").send_keys("cs")
        # 11 | type | name=Course | 411
        self.driver.find_element(By.NAME, "Course").send_keys("411")
        # 12 | click | css=td:nth-child(6) > input |
        self.driver.find_element(By.CSS_SELECTOR, "td:nth-child(6) > input").click()


if __name__ == "__main__":
    test = Test411withsignin()
    test.setup_method(None)
    test.test_411withsignin()
